services:
  postgres:
    image: postgres:16-alpine
    container_name: bav-postgres
    environment:
      POSTGRES_USER: bav
      POSTGRES_PASSWORD: bav
      POSTGRES_DB: bav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bav -d bav"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:7
    container_name: bav-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: bav-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  localstack:
    image: localstack/localstack:3.8
    container_name: bav-localstack
    environment:
      SERVICES: s3,events,sqs
      DEBUG: 0
      AWS_DEFAULT_REGION: eu-west-2
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: bav-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  localstack_data:
