import { GlassCard } from '@/components/ui';

export type Brief = { headline: string; bullets: string[]; updatedAt: string };

/**
 * Daily brief card. The headline + bullets render here. Generation runs nightly
 * against the live commerce + RMA data and writes a snapshot the UI reads.
 */
export function AiBrief({ brief }: { brief: Brief }) {
  return (
    <GlassCard className="relative overflow-hidden p-6">
      <div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-brand-green/10 blur-3xl" />
      <div className="relative">
        <div className="flex items-center justify-between">
          <span className="inline-flex items-center gap-2 font-mono text-caption uppercase tracking-widest text-ink-500">
            <span className="inline-block h-1.5 w-1.5 animate-pulse-green rounded-full bg-brand-green" />
            Today&apos;s brief
          </span>
          <span className="font-mono text-caption text-ink-500">{new Date(brief.updatedAt).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</span>
        </div>
        <h3 className="mt-3 font-display text-h3 font-semibold leading-snug tracking-[-0.02em]">
          {brief.headline || 'No brief generated yet.'}
        </h3>
        {brief.bullets.length > 0 ? (
          <ul className="mt-4 space-y-2 text-small text-ink-700 dark:text-ink-300">
            {brief.bullets.map((b, i) => (
              <li key={i} className="flex gap-2">
                <span aria-hidden className="mt-1.5 inline-block h-1 w-1 shrink-0 rounded-full bg-brand-green" />
                <span>{b}</span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-4 text-small text-ink-500">Nothing noteworthy to report.</p>
        )}
        <div className="mt-4 font-mono text-caption text-ink-500">Generated by Mickai</div>
      </div>
    </GlassCard>
  );
}
